"""Guard the auto-generated "Domain Map" block in docs/manual/index.md.

Companion to tests/test_skill_contracts.py::test_tool_catalog_matches_live_registry
— that test guards docs/manual/tool-catalog.md, this one guards the
docs/manual/index.md "Domain Map" table. Both are regenerated by
`python3 scripts/sync_metadata.py --fix`.

Catches the 2026-07-09 review finding: 8/56 Domain Map rows wrong, 3 domains
(creative_director, audit, grader) missing entirely, and layer-header totals
that didn't match their own rows. Prevents that class of drift from
reappearing silently.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


def test_domain_map_block_matches_live_registry():
    """docs/manual/index.md's Domain Map block must match the live registry."""
    from scripts import sync_metadata

    issues = sync_metadata.check_domain_map()
    assert not issues, (
        "docs/manual/index.md Domain Map is stale relative to the live tool "
        "registry. Run `python3 scripts/sync_metadata.py --fix`:\n"
        + "\n".join(issues)
    )


def test_domain_map_generator_covers_every_live_domain():
    """Every domain the live registry reports must have a DOMAIN_LAYER +
    DOMAIN_SCOPE entry in scripts/generate_tool_catalog.py.

    generate_domain_map() already raises ValueError for this case; this test
    turns that into an explicit, named failure instead of a --check flowing
    through a generic subprocess-stderr message.
    """
    from scripts import generate_tool_catalog as gtc

    tools = gtc.get_tools()
    counts = gtc.get_raw_domain_counts(tools)
    missing = sorted(
        set(counts) - set(gtc.DOMAIN_LAYER) - set(gtc.DOMAIN_SCOPE)
    )
    assert not missing, (
        "New domain(s) shipped without a docs/manual/index.md entry — add "
        f"DOMAIN_LAYER + DOMAIN_SCOPE rows in scripts/generate_tool_catalog.py "
        f"for: {', '.join(missing)}"
    )


def test_domain_map_total_matches_tool_count():
    """Sum of per-domain counts in the generated block equals the total tool count."""
    from scripts import generate_tool_catalog as gtc

    tools = gtc.get_tools()
    counts = gtc.get_raw_domain_counts(tools)
    assert sum(counts.values()) == len(tools)
