"""Device Forge MCP tools — generate M4L devices from gen~ code.

3 tools for the device_forge domain.
"""

from __future__ import annotations

import asyncio
import tempfile
from pathlib import Path

from fastmcp import Context

from ..server import mcp
from .models import DeviceSpec, DeviceType, GenExprParam
from .builder import build_device, ABLETON_USER_LIBRARY, _SUBDIR_MAP
from .templates import get_template, list_templates, list_categories


@mcp.tool()
async def generate_m4l_effect(
    ctx: Context,
    name: str,
    gen_code: str,
    description: str = "Generated by LivePilot Device Forge",
    device_type: str = "audio_effect",
    params: list[dict] | None = None,
    install: bool = True,
) -> dict:
    """Generate a Max for Live device from gen~ codebox code.

    The gen_code parameter accepts GenExpr DSP code that will be compiled
    at runtime by Max's gen~ engine. Safety clipping is automatically added.

    Args:
        name: Device name (used for filename and display)
        gen_code: GenExpr source code for the gen~ codebox
        description: Device description
        device_type: "audio_effect", "midi_effect", "instrument", "midi_generator", or "midi_transformation"
        params: List of parameter dicts with keys: name, default, min_val, max_val, unit_style
        install: If True, copy to Ableton User Library automatically
    """
    type_map = {
        "audio_effect": DeviceType.AUDIO_EFFECT,
        "midi_effect": DeviceType.MIDI_EFFECT,
        "instrument": DeviceType.INSTRUMENT,
        "midi_generator": DeviceType.MIDI_GENERATOR,
        "midi_transformation": DeviceType.MIDI_TRANSFORMATION,
    }
    dt = type_map.get(device_type)
    if dt is None:
        return {"error": f"INVALID_PARAM: Invalid device_type: {device_type}. Use one of: {', '.join(type_map)}"}

    parsed_params = []
    if params:
        for p in params:
            if not isinstance(p, dict) or "name" not in p:
                return {"error": f"INVALID_PARAM: each param requires a 'name' key, got: {p!r}"}
            parsed_params.append(GenExprParam(
                name=p["name"],
                default=p.get("default", 0.5),
                min_val=p.get("min_val", 0.0),
                max_val=p.get("max_val", 1.0),
                unit_style=p.get("unit_style", 1),
            ))

    spec = DeviceSpec(
        name=name,
        device_type=dt,
        gen_code=gen_code,
        description=description,
        params=parsed_params,
    )

    if install:
        subdir = _SUBDIR_MAP[dt]
        output_dir = ABLETON_USER_LIBRARY / subdir
    else:
        # Reuse ONE forge directory under the system temp instead of spawning a
        # fresh mkdtemp() per call (those accumulated, never cleaned). The .amxd
        # is the returned deliverable so it must persist for the caller.
        output_dir = Path(tempfile.gettempdir()) / "livepilot_forge"

    # build_device does blocking filesystem I/O (mkdir + write_bytes). This is
    # an async tool running on the event loop, so offload to a worker thread to
    # avoid freezing all other handlers + the bridge UDP endpoint.
    path = await asyncio.to_thread(build_device, spec, output_dir)

    return {
        "status": "created",
        "name": spec.name,
        "filename": spec.safe_filename,
        "path": str(path),
        "device_type": device_type,
        "installed": install,
        "param_count": len(parsed_params),
        "hint": "Device will appear in Ableton's browser. Use find_and_load_device to load it onto a track.",
    }


@mcp.tool()
async def list_genexpr_templates(
    ctx: Context,
    category: str = "",
) -> dict:
    """List available gen~ DSP building block templates.

    Templates are pre-built GenExpr algorithms that can be used directly
    or as starting points for custom devices. Each template has working
    code, parameters, and descriptions.

    Args:
        category: Filter by category (chaos, delay, distortion, filter, modulation, synthesis, texture, utility). Empty = all.
    """
    templates = list_templates(category=category)
    categories = list_categories()

    return {
        "templates": templates,
        "count": len(templates),
        "categories": sorted(categories),
        "hint": "Use generate_m4l_effect with a template's code to create a device, or write custom GenExpr.",
    }


def _install_m4l_device_sync(source_path: str) -> dict:
    """Blocking filesystem work for install_m4l_device (read/mkdir/write).

    Run via asyncio.to_thread from the async tool below so the event loop
    (and the bridge UDP endpoint) never stalls on disk I/O.
    """
    src = Path(source_path)
    if not src.exists():
        return {"error": f"File not found: {source_path}"}
    if src.suffix != ".amxd":
        return {"error": f"Not an .amxd file: {source_path}"}

    data = src.read_bytes()
    if len(data) < 12 or data[:4] != b"ampf":
        return {"error": "Invalid .amxd file — missing ampf header"}

    marker = data[8:12]
    type_map = {
        b"aaaa": (DeviceType.AUDIO_EFFECT, "audio_effect"),
        b"mmmm": (DeviceType.MIDI_EFFECT, "midi_effect"),
        b"iiii": (DeviceType.INSTRUMENT, "instrument"),
        b"nagg": (DeviceType.MIDI_GENERATOR, "midi_generator"),
        b"natt": (DeviceType.MIDI_TRANSFORMATION, "midi_transformation"),
    }
    dt_info = type_map.get(marker)
    if dt_info is None:
        return {"error": f"Unknown device type marker: {marker}"}

    dt, type_name = dt_info
    subdir = _SUBDIR_MAP[dt]
    dest_dir = ABLETON_USER_LIBRARY / subdir
    dest_dir.mkdir(parents=True, exist_ok=True)

    dest = dest_dir / src.name
    dest.write_bytes(data)

    return {
        "status": "installed",
        "filename": src.name,
        "device_type": type_name,
        "path": str(dest),
        "hint": "Device now available in Ableton's browser.",
    }


@mcp.tool()
async def install_m4l_device(
    ctx: Context,
    source_path: str,
) -> dict:
    """Copy a .amxd file to Ableton's User Library.

    Args:
        source_path: Path to the .amxd file to install
    """
    return await asyncio.to_thread(_install_m4l_device_sync, source_path)
